language: php
php:
  - 7.0
  - 7.1
install:
  # ImageMagick
  #- printf "\n" | pecl install imagick
  # Composer
  - rm -rf ./*
  - composer self-update
  - composer create-project bluzphp/skeleton --stability=dev
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
  # composer require
  - cd skeleton
  - ENV=default composer require bluzphp/module-test
  # Newman
  - npm install -g newman@1
script:
  - mkdir .reports
  # Code style
  - php vendor/bin/phpcs ./application --standard=PSR1,PSR2 --encoding=utf-8 --ignore=./application/_loader.php
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration ./phpunit.xml.dist --coverage-clover=.reports/clover.xml
  # WebServer run
  - nohup bash -c "php -S 127.0.0.1:8000 -t ./public/ ./public/routing.php 2>&1 &" && sleep 1; cat nohup.out
  # Newman run
  - newman -k -c tests/postman/collection.json -e tests/postman/environment.json -x -t .reports/newman.xml -O .reports/newman.log
  - newman -k -c tests/postman/test/collection.json -e tests/postman/test/environment.json -x -t .reports/newman.xml -O .reports/newman.log
after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover .reports/clover.xml
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
branches:
  only:
  - master
  - develop
