language: php
php:
  - 7.4
  - 8.0
  - 8.1
matrix:
  allow_failures:
    - php: 8.0
    - php: 8.1
install:
  # Composer
  - composer self-update
  - composer install
script:
  # Code style
  - php vendor/bin/phpcs ./src --standard=PSR12 --encoding=utf-8
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration ./phpunit.xml.dist
notifications:
  email: false
branches:
  only:
  - master
  - develop
