language: php
php:
  - 7.3
  - 7.4
  - master
matrix:
  allow_failures:
    - php: master
install:
  # Composer
  - composer self-update
  - composer install
script:
  # Code style
  - php vendor/bin/phpcs ./src --standard=PSR12 --encoding=utf-8
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration ./phpunit.xml.dist
notifications:
  email: false
branches:
  only:
  - master
  - develop
